apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: jenkins
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mon-application
  template:
    metadata:
      labels:
        app: mon-application
    spec:
      containers:
      - name: nodejs-app
        image: arwaoueriemmi/app_image:v101.0 
        ports:
        - containerPort: 3000  
