apiVersion: v1
kind: Service
metadata:
  name: mon-service
  namespace: jenkins
spec:
  selector:
    app: mon-application
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 3000
